version: '3'

services:
  kafka:
    image: bitnami/kafka:3.5
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:${KAFKA_PORT_1},CONTROLLER://:${KAFKA_PORT_2}
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:${KAFKA_PORT_2}
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE=true   
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:${KAFKA_PORT_1}
      - KAFKA_CFG_INTER_BROKER_LISTENER_NAME=PLAINTEXT 
    ports:
      - "${KAFKA_PORT_1}:${KAFKA_PORT_1}"
      - "${KAFKA_PORT_2}:${KAFKA_PORT_2}"
    expose:
      - "${KAFKA_PORT_1}"
      - "${KAFKA_PORT_2}"
    networks:
      - app-tier

  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"
    expose:
      - "${DATABASE_PORT}"
    networks:
      - app-tier

networks:
  app-tier:
    driver: bridge